# Generated by Django 4.0.4 on 2022-05-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=200)),
                ('time_posted', models.TimeField()),
                ('user_id', models.IntegerField()),
                ('meeting_minutes', models.TextField()),
            ],
        ),
    ]
