# Generated by Django 4.0.4 on 2022-05-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
