# Generated by Django 4.0.4 on 2022-05-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0004_meetings_files_url_alter_meetings_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='21/05/2022 09:58:22', max_length=15, unique=True),
        ),
    ]
