# Generated by Django 4.0.4 on 2022-05-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0005_alter_meetings_time_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetings',
            old_name='files_url',
            new_name='file_url',
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='21/05/2022 10:00:32', max_length=15, unique=True),
        ),
    ]
