# Generated by Django 4.0.4 on 2022-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0006_rename_files_url_meetings_file_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='file_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meeting_minutes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='22/05/2022 19:27:48', max_length=30),
        ),
    ]
