# Generated by Django 4.0.4 on 2022-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0008_alter_meetings_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='22/05/2022 21:21:58', max_length=30),
        ),
    ]
