# Generated by Django 4.0.4 on 2022-05-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0009_alter_meetings_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='file_url',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meeting_minutes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='22/05/2022 22:01:07', max_length=30),
        ),
    ]
