# Generated by Django 4.0.4 on 2022-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetingApi', '0011_alter_meetings_time_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='time_posted',
            field=models.CharField(default='23/05/2022 14:11:31', max_length=30),
        ),
    ]
